cc_library(
    name = "libnos_citadel_linux",
    srcs = [
        "LinuxCitadelClient.cpp",
    ],
    hdrs = [
        "include/nos/LinuxCitadelClient.h",
    ],
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@nugget_core_nugget//:driver",
        "@nugget_host_generic_libnos//:libnos_common",
    ],
)
