cc_library(
    name = "libnos_common",
    srcs = [
        "NuggetClient.cpp",
    ],
    hdrs = [
        "include/nos/AppClient.h",
        "include/nos/NuggetClient.h",
    ],
    includes = [
        "./include",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@nugget_core_nugget//:driver",
    ],
)
