// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nugget/protobuf/options.proto

#ifndef PROTOBUF_nugget_2fprotobuf_2foptions_2eproto__INCLUDED
#define PROTOBUF_nugget_2fprotobuf_2foptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)

namespace nugget {
namespace protobuf {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_nugget_2fprotobuf_2foptions_2eproto();
void protobuf_AssignDesc_nugget_2fprotobuf_2foptions_2eproto();
void protobuf_ShutdownFile_nugget_2fprotobuf_2foptions_2eproto();


// ===================================================================


// ===================================================================

static const int kAppIdFieldNumber = 2000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  app_id;
static const int kAppNameFieldNumber = 2001;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  app_name;
static const int kAppVersionFieldNumber = 2002;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 >, 13, false >
  app_version;
static const int kRequestBufferSizeFieldNumber = 2003;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 >, 13, false >
  request_buffer_size;
static const int kResponseBufferSizeFieldNumber = 2004;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 >, 13, false >
  response_buffer_size;

// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace nugget

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_nugget_2fprotobuf_2foptions_2eproto__INCLUDED
