// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nugget/protobuf/options.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "nugget/protobuf/options.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace nugget {
namespace protobuf {

namespace {


}  // namespace


void protobuf_AssignDesc_nugget_2fprotobuf_2foptions_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_nugget_2fprotobuf_2foptions_2eproto() {
  protobuf_AddDesc_nugget_2fprotobuf_2foptions_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "nugget/protobuf/options.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_nugget_2fprotobuf_2foptions_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_nugget_2fprotobuf_2foptions_2eproto() {
}

void protobuf_AddDesc_nugget_2fprotobuf_2foptions_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_nugget_2fprotobuf_2foptions_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\035nugget/protobuf/options.proto\022\017nugget."
    "protobuf\032 google/protobuf/descriptor.pro"
    "to:0\n\006app_id\022\037.google.protobuf.ServiceOp"
    "tions\030\320\017 \001(\t:2\n\010app_name\022\037.google.protob"
    "uf.ServiceOptions\030\321\017 \001(\t:5\n\013app_version\022"
    "\037.google.protobuf.ServiceOptions\030\322\017 \001(\r:"
    "=\n\023request_buffer_size\022\037.google.protobuf"
    ".ServiceOptions\030\323\017 \001(\r:>\n\024response_buffe"
    "r_size\022\037.google.protobuf.ServiceOptions\030"
    "\324\017 \001(\r", 366);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "nugget/protobuf/options.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::ServiceOptions::default_instance(),
    2000, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::ServiceOptions::default_instance(),
    2001, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::ServiceOptions::default_instance(),
    2002, 13, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::ServiceOptions::default_instance(),
    2003, 13, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::ServiceOptions::default_instance(),
    2004, 13, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_nugget_2fprotobuf_2foptions_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_nugget_2fprotobuf_2foptions_2eproto {
  StaticDescriptorInitializer_nugget_2fprotobuf_2foptions_2eproto() {
    protobuf_AddDesc_nugget_2fprotobuf_2foptions_2eproto();
  }
} static_descriptor_initializer_nugget_2fprotobuf_2foptions_2eproto_;
const ::std::string app_id_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  app_id(kAppIdFieldNumber, app_id_default);
const ::std::string app_name_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  app_name(kAppNameFieldNumber, app_name_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 >, 13, false >
  app_version(kAppVersionFieldNumber, 0u);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 >, 13, false >
  request_buffer_size(kRequestBufferSizeFieldNumber, 0u);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 >, 13, false >
  response_buffer_size(kResponseBufferSizeFieldNumber, 0u);

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace nugget

// @@protoc_insertion_point(global_scope)
