workspace(name = "nugget_host_generic_libnos_transport")

new_http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/release-1.8.0.zip",
    build_file = "../../../core/nugget/BUILD.gtest",
    sha256 = "f3ed3b58511efd272eb074a3a6d6fb79d7c2e6a0e374323d1e6bcbcc1ef141bf",
    strip_prefix = "googletest-release-1.8.0",
)

local_repository(
    name = "nugget_host_generic",
    path = "../../../host/generic",
)

local_repository(
    name = "nugget_host_generic_libnos_datagram",
    path = "../../../host/generic/libnos_datagram",
)
